In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
heart = pd.read_csv('heart.csv')
heart

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [3]:
heart['target'].unique() # classification maa output categorical hunxa.

array([0, 1], dtype=int64)

In [4]:
heart['exang'].unique()

array([0, 1], dtype=int64)

In [5]:
heart['oldpeak'].unique()

array([1. , 3.1, 2.6, 0. , 1.9, 4.4, 0.8, 3.2, 1.6, 3. , 0.7, 4.2, 1.5,
       2.2, 1.1, 0.3, 0.4, 0.6, 3.4, 2.8, 1.2, 2.9, 3.6, 1.4, 0.2, 2. ,
       5.6, 0.9, 1.8, 6.2, 4. , 2.5, 0.5, 0.1, 2.1, 2.4, 3.8, 2.3, 1.3,
       3.5])

In [6]:
heart['slope'].unique()

array([2, 0, 1], dtype=int64)

In [7]:
heart['thal'].unique()

array([3, 2, 1, 0], dtype=int64)

In [8]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [11]:
heart.duplicated().sum()

723

In [12]:
heart.drop_duplicates(inplace= True)

In [13]:
heart.shape

(302, 14)

In [27]:
heart['target'].unique()

array([0, 1], dtype=int64)

In [28]:
X = heart.drop(columns = 'target')
y = heart['target']

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [36]:
# objects
lgr = LogisticRegression()
svc = SVC()
knn = KNeighborsClassifier(n_neighbors= 5 ) # odd
dtc = DecisionTreeClassifier()
rfc = RandomForestClassifier()

In [37]:
lgr.fit(X_train, y_train)
svc.fit(X_train, y_train)
knn.fit(X_train, y_train)
dtc.fit(X_train, y_train)
rfc.fit(X_train, y_train)

C:\Users\Acer\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


RandomForestClassifier()

In [38]:
lgr

LogisticRegression()

In [39]:
svc

SVC()

In [40]:
rfc

RandomForestClassifier()

In [41]:
knn

KNeighborsClassifier()

In [42]:
dtc

DecisionTreeClassifier()

In [43]:
predict_lgr = lgr.predict(X_test)
predict_svc = svc.predict(X_test)
predict_knn = knn.predict(X_test)
predict_dtc = dtc.predict(X_test)
predict_rfc = rfc.predict(X_test)

In [47]:
print(predict_lgr,'\n',predict_svc,'\n',predict_knn,'\n',predict_dtc,'\n',predict_rfc)

[1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1
 1 0 0 0 0 1 1 0 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0 1] 
 [1 0 0 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 0
 1 0 0 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 0 0 1 1 0 1] 
 [1 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 1 1 0 1 1 0 0 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 0 1 1 0 0 1 1 0 0 1 1 0 1 1 1 1 1] 
 [1 1 0 0 1 0 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0
 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 0 0 0] 
 [1 0 0 0 1 0 0 1 1 1 1 0 1 1 1 0 0 1 0 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1
 1 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1]


# Evaluation

In [48]:
from sklearn import metrics

In [49]:
metrics.confusion_matrix(y_test, predict_lgr)

array([[22, 10],
       [ 2, 27]], dtype=int64)

In [68]:
acc_lgr = metrics.accuracy_score(y_test, predict_lgr)
pre_lgr = metrics.precision_score(y_test, predict_lgr)
rec_lgr = metrics.recall_score(y_test, predict_lgr)
f1_lgr = metrics.f1_score(y_test, predict_lgr)

In [50]:
metrics.confusion_matrix(y_test, predict_svc)

array([[12, 20],
       [ 5, 24]], dtype=int64)

In [67]:
acc_svc = metrics.accuracy_score(y_test, predict_svc)
pre_svc = metrics.precision_score(y_test, predict_svc)
rec_svc = metrics.recall_score(y_test, predict_svc)
f1_svc = metrics.f1_score(y_test, predict_svc)

In [51]:
metrics.confusion_matrix(y_test, predict_knn)

array([[14, 18],
       [ 4, 25]], dtype=int64)

In [66]:
acc_knn = metrics.accuracy_score(y_test, predict_knn)
pre_knn = metrics.precision_score(y_test, predict_knn)
rec_knn = metrics.recall_score(y_test, predict_knn)
f1_knn = metrics.f1_score(y_test, predict_knn)

In [52]:
metrics.confusion_matrix(y_test, predict_dtc)

array([[26,  6],
       [ 9, 20]], dtype=int64)

In [65]:
acc_dtc = metrics.accuracy_score(y_test, predict_dtc)
pre_dtc = metrics.precision_score(y_test, predict_dtc)
rec_dtc = metrics.recall_score(y_test, predict_dtc)
f1_dtc = metrics.f1_score(y_test, predict_dtc)

In [53]:
metrics.confusion_matrix(y_test, predict_rfc)

array([[25,  7],
       [ 3, 26]], dtype=int64)

In [64]:
acc_rfc = metrics.accuracy_score(y_test, predict_rfc)
pre_rfc = metrics.precision_score(y_test, predict_rfc)
rec_rfc = metrics.recall_score(y_test, predict_rfc)
f1_rfc = metrics.f1_score(y_test, predict_rfc)

In [63]:
print(acc_lgr, acc_svc, acc_knn, acc_dtc, acc_rfc)

0.8032786885245902 0.5901639344262295 0.639344262295082 0.7540983606557377 0.8360655737704918


In [69]:
print(pre_lgr, pre_svc, pre_knn, pre_dtc, pre_rfc)

0.7297297297297297 0.5454545454545454 0.5813953488372093 0.7692307692307693 0.7878787878787878


In [70]:
print(rec_lgr, rec_svc, rec_knn, rec_dtc, rec_rfc)

0.9310344827586207 0.8275862068965517 0.8620689655172413 0.6896551724137931 0.896551724137931


In [71]:
print(f1_lgr, f1_svc, f1_knn, f1_dtc, f1_rfc)

0.8181818181818181 0.6575342465753425 0.6944444444444445 0.7272727272727274 0.8387096774193549


In [72]:
X.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [74]:
data = {
    'age': 40, 
    'sex' : 1 , 
    'cp' : 1, 
    'trestbps' : 130, 
    'chol' : 210 , 
    'fbs' : 1, 
    'restecg' : 0, 
    'thalach' : 161 ,
    'exang' :1 , 
    'oldpeak' : 2.0, 
    'slope' : 0 , 
    'ca' : 3,
    'thal': 2
}
df = pd.DataFrame(data, index = [0])
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   40    1   1       130   210    1        0      161      1      2.0      0   

   ca  thal  
0   3     2

In [75]:
rfc.predict(df)

array([1], dtype=int64)

# save models

In [77]:
import joblib

In [78]:
rfc = RandomForestClassifier()
rfc.fit(X, y)

RandomForestClassifier()

In [79]:
joblib.dump(rfc, 'rfc_model')

['rfc_model']

In [80]:
rfc_model = joblib.load('rfc_model')

In [84]:
predict = rfc_model.predict(df)[0]
if predict == 1:
    print("There might be high chance of getting heart attack.")
else:
    print("There might be less chance of getting heart attack.")

There might be high chance of getting heart attack.
